apply plugin: 'com.android.application'

repositories {
    mavenCentral()
    /*flatDir {
        dirs 'libs'
    }*/
}
android {
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    defaultConfig {
        applicationId "com.advira.advirafarm.buyer"
        minSdkVersion 21
        targetSdkVersion 31
        compileSdkVersion 31
        //buildToolsVersion "30.0.3"
        versionCode 31
        versionName "1.30"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        multiDexEnabled true
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation":"$projectDir/schemas".toString()]
            }
        }
    }
    buildTypes {
            debug {
                minifyEnabled false
                debuggable false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    aaptOptions {
        cruncherEnabled = false
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    buildFeatures {
        viewBinding true
    }
    dataBinding.enabled = true
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.6.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "com.google.firebase:firebase-auth:21.0.4"
    implementation 'com.google.firebase:firebase-core:21.0.0'
    implementation 'com.google.firebase:firebase-messaging:23.0.5'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'com.google.firebase:firebase-crashlytics:18.2.10'
    implementation 'com.google.firebase:firebase-analytics:21.0.0'
    implementation 'com.google.firebase:firebase-config:21.1.0'
    implementation platform('com.google.firebase:firebase-bom:29.3.1')
    implementation 'com.google.firebase:firebase-inappmessaging-display:20.1.2'
    implementation 'com.google.firebase:firebase-perf:20.0.6'
    implementation 'com.google.android.libraries.places:places:2.6.0'
    implementation 'com.google.firebase:firebase-database:20.0.5'
    implementation 'com.firebaseui:firebase-ui-database:6.2.1'
    implementation 'com.google.firebase:firebase-firestore:24.1.2'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation ("androidx.test.espresso:espresso-core:3.4.0", {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.roughike:bottom-bar:2.3.1'
    implementation 'com.synnapps:carouselview:0.1.4'
    implementation 'com.squareup.picasso:picasso:2.5.2'

    //Retrofit
    implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'com.squareup.okhttp3:okhttp:5.0.0-alpha.2'
    implementation 'com.squareup.okhttp:okhttp-urlconnection:2.7.5'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.2'
    implementation('com.squareup.retrofit2:retrofit:2.9.0') {
        //exclude module: 'okhttp'
    }

    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.github.chrisbanes:PhotoView:2.1.3'
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    //Butterknife
    implementation 'com.jakewharton:butterknife:10.2.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.3'
    //dexter permissions
    implementation 'com.karumi:dexter:6.2.3'
    // circular imageview
    implementation 'com.mikhaellopez:circularimageview:3.2.0'
    //Recycler View
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.recyclerview:recyclerview-selection:1.1.0'
    //Glide
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    implementation 'com.github.bumptech.glide:annotations:4.13.1'
    implementation('com.github.bumptech.glide:okhttp3-integration:4.12.0') {
        exclude group: 'glide-parent'
    }
    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.1'
    implementation ("com.github.bumptech.glide:glide:4.12.0") {
        exclude group: "com.android.support"
    }
    implementation ("com.github.bumptech.glide:glide:4.12.0@aar") {
        transitive = true
    }

    annotationProcessor 'androidx.annotation:annotation:1.3.0'
    implementation 'com.github.yalantis:ucrop:2.2.4'
    implementation 'com.agrawalsuneet.androidlibs:dotsloader:1.4'
    implementation 'com.white:progressview:1.0.1'
    implementation 'com.github.castorflex.smoothprogressbar:library:1.1.0'
    implementation 'com.google.android.gms:play-services-maps:18.0.2'
    implementation 'com.google.maps.android:android-maps-utils:2.2.0'
    implementation 'com.google.android.gms:play-services-location:19.0.1'
    implementation 'com.github.mancj:MaterialSearchBar:0.8.2'
    implementation 'com.skyfishjy.ripplebackground:library:1.0.1'
    //for API place autocomplete
    implementation 'com.google.android.gms:play-services-places:17.0.0'
    implementation 'com.github.transferwise:sequence-layout:1.0.7'
    //Play store
    implementation 'com.google.android.play:core:1.10.3'
    implementation 'com.google.android.gms:play-services-auth:20.2.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:18.0.1'

    // paytm dependency
    implementation('com.paytm:pgplussdk:1.2.3') {
        transitive = true
    }
    implementation 'com.mikhaellopez:circularimageview:3.2.0'
    implementation 'com.pranavpandey.android:dynamic-toasts:3.3.1'
    implementation(name: 'razorpay-android-3.8.8',ext :'aar')
    //implementation(name: 'razorpay-amazonpay-1.3.0', ext: 'aar')
    //implementation(name: 'PayWithAmazon', ext: 'aar')
    //implementation 'com.razorpay:checkout:1.6.13'
    implementation 'com.android.support:customtabs:26.1.0'
    implementation 'androidx.browser:browser:1.4.0'
    implementation 'me.relex:circleindicator:1.2.1@aar'

    //In-app Update
    implementation 'eu.dkaratzas:android-inapp-update:1.0.5'
    //Paging Library
    implementation 'android.arch.paging:runtime:1.0.1'
    //Horizental calander view*/
    //implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation 'noman.weekcalendar:weekcalendar:1.0.6'
    implementation 'com.vivekkaushik.datepicker:datePickerTimeline:0.0.1'
    implementation 'com.github.huzaifa0024:Horizontal-Calendar:v1.1.5'
    implementation 'com.github.mahimrocky:WeekDaySelector:1.0.0'
    //SMS AUTOREAD
    implementation 'com.github.stfalcon:smsverifycatcher:0.3.2'
    implementation 'androidx.multidex:multidex:2.0.1'
    //multiDexEnabled true
    //collapsible Calander
    implementation 'com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.0'
    implementation "androidx.core:core-ktx:1.7.0"
    //implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10"
    //PinViewOTP
    implementation 'io.github.chaosleung:pinview:1.4.4'

    // Testing
    androidTestImplementation ("androidx.test.espresso:espresso-core:$rootProject.espressoVersion", {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //Room Persistence
    implementation 'android.arch.persistence.room:runtime:1.1.1'
    annotationProcessor 'android.arch.persistence.room:compiler:1.1.1'
    testImplementation'android.arch.persistence.room:testing:1.1.1'
    implementation 'android.arch.persistence.room:rxjava2:1.1.1'
    // Lifecycle components
    implementation "android.arch.lifecycle:runtime:1.1.1"
    implementation 'android.arch.lifecycle:extensions:1.1.1'
    //noinspection LifecycleAnnotationProcessorWithJava8
    annotationProcessor 'android.arch.lifecycle:compiler:1.1.1'

    //fresco ImageLoader
    implementation 'com.facebook.fresco:fresco:2.6.0'
    //Shimmer
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
